spring.datasource.url=jdbc:mysql://mainline.proxy.rlwy.net:44724/railway
spring.datasource.username=root
spring.datasource.password=EVXIQTuXvaMWtHcUXQsrQPjZiuhbOCig

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true